# A short, descriptive name of this building block collection
name: OGC Incubator Building Blocks repository

# Short abstract for this collection (optional)
abstract: |
  Building Blocks for reuse, yet to be managed formally within a SWG charter scope.

# Description for this collection (optional)
# description:

# Customize the following prefix (will be prepended to the path of the building blocks):
identifier-prefix: ogc.

# List of imports ("default" is an alias for the main OGC Building Blocks Register)
imports:
  - https://github.com/ogcincubator/bblock-prov-schema/build/register.json
  - https://github.com/ogcincubator/topo-feature/build/register.json
  - https://github.com/ogcincubator/geodcat-ogcapi-records/build/register.json
  - https://github.com/ogcincubator/bblocks-ogcapi-records/build/register.json
  - https://github.com/ogcincubator/prov-cwl/build/register.json

# SPARQL configuration (optional)
#   Authentication can be set through the sparql_username and sparql_password GitHub Workflow inputs
#   (see .github/workflow/process-bblocks.yml)
#
# sparql:
#   push: https://example.com/gsp           # SPARQL Graph Store Protocol endpoint for uploading data
#   graph: https://my.bblocks.example.com/  # SPARQL Graph where data will be uploaded
#                                           #  if left empty, the base URL for the publication will be used
#   query: https://example.com/sparql       # SPARQL query endpoint where data will be available
